# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -o ./gtest

    - name: Upload to Release Action
      # You may pin to the exact commit or the version.
      # uses: Shopify/upload-to-release@9942a4c936dab172f7101dcc7dc20528ea949102
      uses: Shopify/upload-to-release@v1.0.1
      with:
        id: Upload_to_Release_Action
        # Artifact name
        name: gtest1
        # Path to the file to upload
        path: ./gtest
        # Content type for the file
        content-type: # optional, default is application/octet-stream
        # secrets.GITHUB_TOKEN
        repo-token: ${{secrets.GITHUB_TOKEN}}

